#!/bin/bash

echo "<html>" > route
echo "<body>" >> route
echo "<h1>Here is your commute.<h1>" >> route
echo "<a href=\"https://www.waze.com/livemap?at=now&from_lat=$HOME_LAT&from_lon=$HOME_LON&to_lat=$WORK_LAT&to_lon=$WORK_LON\">Click here</a>" > route
echo "</body>" >> route
echo "</html>" >> route

mutt -s "Commute" $EMAIL < ./route

#echo "https://www.waze.com/livemap?at=now&from_lat=$WORK_LAT&from_lon=$WORK_LON&to_lat=$HOME_LAT&to_lon=$HOME_LON" > to_home
